on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test job1"
          echo "test job2"
          echo "test job3"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test job1"
          echo "test job2"
          echo "test job3"
      - run: sleep 3600

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test job1"
          echo "test job2"
          echo "test job3"
          sleep 3600
